#ifndef FILE_MACROS_H
#define FILE_MACROS_H

#define FILE_MAX_ROOMS 64
#define FILE_MAX_ROOM_MESSAGE_LENGTH 200
#define FILE_MAX_CHALLENGES_PER_ROOM 8
#define FILE_INTRO_TEXT_MAX_LENGTH 80
#define FILE_MAX_FILE_LINE_LENGTH 203
#define FILE_CONFIG_FILE_NAME "config.txt"

#endif
